[install]
# Workspace install behavior
exact = false
peer = true
production = false
optional = true
dev = true

linkWorkspacePackages = true

dedupe = ["next", "react", "react-dom", "@types/react", "@types/react-dom"]

[install.scopes]

[install.cache]
disable = false
disableManifest = false

[run]
bun = true
